### ISSUE TITLE
Demo Website No Longer Functional

### ISSUE THREAD

**Issue by hc970** [c-a-m/passfault#50]
Hello,

Apologies if this is not the correct means of reporting this issue.
The demo site at this time appears to be down, I’m receiving a HTTP 404 error:

https://passfault.appspot.com/password_strength.html

The following website also shows the site is down:

http://www.isitdownrightnow.com/passfault.appspot.com.html

I realize that you are probably aware of this and apologize if I’m reporting the obvious to you. Thanks for your time.

**Comment by c-a-m** [comment]
Thanks @hc970 I was not aware of this.  I'll look into it right away!

**Comment by c-a-m** [comment]
Oh.  I know what it is.  The app-engine setup I've been using is an older deprecated version and they've finally pulled the plug on it.  I need to resetup the page.  Thanks for the heads up!

**Comment by c-a-m** [comment]
I've got passfault deployed to an upgraded location: https://passfault-hrd.appspot.com and got DNS for http://passfault.com  pointing to the right place.  I need to wait a few days to change the the https://passfault.appspot... domain

**Comment by hc970** [comment]
Hello Cam,

Many thanks for resolving this issue so quickly. I use Passfault a lot and it's great to have it back again. I donated a small amount to OWASP last week and hope to give more sometime in the near future.

If you wish me to close this issue as resolved, I will do so. Keep up the excellent work. Thanks again.

**Comment by c-a-m** [comment]
Great to hear! I've put a lot into passfault and it's great to hear that it's being useful.  

I'd like to keep this open until I fix the appspot domain, since many people have linked directly to it.
